pipelines:
  custom: # Pipelines that can only be triggered manually
    qa:
      - step:
          script:
            - echo "Manual triggers for QA!"
    staging:
      - step:
          script:
            - echo "Manual triggers for staging!"
  branches:  # Pipelines that run automatically on a commit to a branch can also be triggered manually
    main:
    #staging:
      - step:
          name: Installing node.js and npm appcenter-cli
          image: node:19.3.0
          script:
            - echo "Automated pipelines are cool too."
            - node --version
            - npm install --location=global appcenter-cli
            - appcenter apps list --token 7b16f03cb18ba7dad26dc378981e6560c8b1d441
            - appcenter build queue -b main --app testaccoutn/test --token c105225fa414b9e5d5bcef925f400a5150af6610
            #- npm install // node js package manager installation
            #- npm install -g appcenter-cli // install app center cli using node js